version: "2"
services:
  web:
    container_name: engetecnica-web
    build: .
    ports:
    - "8000:80"
    - "9000:443"
    volumes:
    - ./:/var/www/html/
    - ./apache_error_log:/var/log/apache2
    links:
    - db

  db:
    container_name: engetecnica-db
    image: mysql:5.7
    ports:
      - "7000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=engetecnica

    volumes:
    - ./setup/my.cnf:/etc/my.cnf
    - engetecnica:/var/lib/mysql
    restart: unless-stopped

volumes:
  engetecnica:
    external: true
