version: "2"
services:
  web_dev:
    container_name: engetecnica_web_dev
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
    - "8000:80"
    - "9000:443"
    expose: 
      - '80'
      - '443'
    volumes:
    #- ./:/var/www/html/
    - ./log:/var/log/apache2
    networks:
      - engetecnica-network-dev
    links:
      - db

  db:
    container_name: engetecnica_db_dev
    image: mariadb
    ports:
      - "33061:3306"
    expose: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=engetecnica
    volumes:
      - ./setup/my.cnf:/etc/my.cnf
      - engetecnica:/var/lib/mysql
    networks:
      - engetecnica-network-dev
    restart: always

volumes:
  engetecnica:
    external: true
networks:
  engetecnica-network-dev: